export type ChemicalUnit = "L" | "mL" | "µL";
export type ChemicalIngredient = { name: string; quantity?: number; unit?: string; stockValue?: number; stockUnit?: string; form: string; note?: string; finalTopUp?: boolean };
export type ChemicalRecipe = { id: string; name: string; group: string; baseVolume: number; baseUnit: ChemicalUnit; stock: string; note?: string; ingredients: ChemicalIngredient[]; steps: string[]; status?: "Bản nháp" | "Đã duyệt" };

export const seedChemicalRecipes: ChemicalRecipe[] = [
  { id: "pbs", name: "PBS", group: "Dung dịch cơ bản", baseVolume: 1000, baseUnit: "mL", stock: "—", ingredients: [{ name: "Nước cất 2 lần", quantity: 1000, unit: "mL", form: "Lỏng" }, { name: "Gói bột PBS", quantity: 1, unit: "gói", form: "Rắn" }], steps: ["Khuấy tan bột và nước", "Lọc giấy lọc Watman", "Hấp vô trùng và sử dụng"] },
  { id: "glucose", name: "Glucose (250X)", group: "Stock đơn chất", baseVolume: 50, baseUnit: "mL", stock: "250X = 247,75 g/L", note: "Lọc màng 0,22 µm, không hấp", ingredients: [{ name: "Glucose", quantity: 12.388, unit: "g", form: "Rắn", note: "Final conc. 991 mg/L" }, { name: "Nước cất 2 lần", quantity: 40, unit: "mL", form: "Lỏng", note: "Đong trước 40 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 40 mL nước cất", "Cân glucose cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc màng 0,22 µm vô trùng"] },
  { id: "nahco3", name: "NaHCO₃ (250X)", group: "Stock đơn chất", baseVolume: 50, baseUnit: "mL", stock: "250X = 56,75 g/L", note: "Lọc màng 0,22 µm, không hấp", ingredients: [{ name: "NaHCO₃", quantity: 2.838, unit: "g", form: "Rắn", note: "Final conc. 227 mg/L" }, { name: "Nước cất 2 lần", quantity: 40, unit: "mL", form: "Lỏng", note: "Đong trước 40 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 40 mL nước cất", "Cân NaHCO₃ cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc màng 0,22 µm vô trùng"] },
  { id: "cacl2", name: "CaCl₂·2H₂O (250X)", group: "Stock đơn chất", baseVolume: 50, baseUnit: "mL", stock: "250X = 56,25 g/L", ingredients: [{ name: "CaCl₂·2H₂O", quantity: 2.813, unit: "g", form: "Rắn", note: "Final conc. 225 mg/L" }, { name: "Nước cất 2 lần", quantity: 40, unit: "mL", form: "Lỏng", note: "Đong trước 40 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 40 mL nước cất", "Cân CaCl₂·2H₂O cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc giấy lọc Watman và hấp vô trùng"] },
  { id: "hepes", name: "HEPES (100X)", group: "Stock đơn chất", baseVolume: 50, baseUnit: "mL", stock: "100X = 595 g/L", note: "Lọc màng 0,22 µm, không hấp", ingredients: [{ name: "HEPES", quantity: 11.9, unit: "g", form: "Rắn", note: "Final conc. 2380 mg/L" }, { name: "Nước cất 2 lần", quantity: 40, unit: "mL", form: "Lỏng", note: "Đong trước 40 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 40 mL nước cất", "Cân HEPES cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Điều chỉnh pH 7 bằng HCl 1N hoặc NaOH 1N, rồi lọc"] },
  { id: "egta-stock", name: "EGTA (250X)", group: "Stock đơn chất", baseVolume: 50, baseUnit: "mL", stock: "250X = 47,5 g/L", note: "Lọc màng 0,22 µm, không hấp", ingredients: [{ name: "EGTA", quantity: 2.375, unit: "g", form: "Rắn", note: "Final conc. 190 mg/L" }, { name: "Nước cất 2 lần", quantity: 40, unit: "mL", form: "Lỏng", note: "Đong trước 40 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 40 mL nước cất", "Cân EGTA cho vào khuấy tan", "Điều chỉnh pH 7 bằng NaOH từ từ", "Đong nước cất lên đủ thể tích và lọc màng"] },
  { id: "antibiotic", name: "Antibiotic (100X)", group: "Stock hỗn hợp", baseVolume: 100, baseUnit: "mL", stock: "100X", note: "Không hấp; pha theo tỉ lệ 1:3", ingredients: [{ name: "Streptomycin", quantity: 1, unit: "phần", form: "Rắn", note: "Tỉ lệ 1" }, { name: "Gentamicin", quantity: 3, unit: "phần", form: "Lỏng", note: "Tỉ lệ 3" }, { name: "Nước cất vô trùng", quantity: 100, unit: "mL", form: "Lỏng", note: "50 mL trước + 50 mL còn lại" }], steps: ["Cho trước 50 mL nước cất vô trùng", "Cho hai chất kháng sinh vào", "Cho 50 mL nước cất còn lại và sử dụng"] },
  { id: "nycodenz", name: "Nycodenz (80%)", group: "Stock đơn chất", baseVolume: 100, baseUnit: "mL", stock: "80% w/v → 1,426 g/mL", note: "Lọc màng 0,22 µm, không hấp", ingredients: [{ name: "Nycodenz", quantity: 80, unit: "g", form: "Rắn" }, { name: "Nước cất 2 lần", quantity: 50, unit: "mL", form: "Lỏng", note: "Đong trước 50 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 50 mL nước cất", "Cân Nycodenz cho vào khuấy tan", "Đong nước cất lên đủ thể tích và lọc màng"] },
  { id: "salt-1", name: "Muối 1 (10X)", group: "Stock muối", baseVolume: 500, baseUnit: "mL", stock: "10X", ingredients: [{ name: "NaCl", quantity: 40, unit: "g", form: "Rắn", note: "8000 mg/L" }, { name: "KCl", quantity: 1.85, unit: "g", form: "Rắn", note: "370 mg/L" }, { name: "Na₂HPO₄", quantity: 0.298, unit: "g", form: "Rắn", note: "59,6 mg/L" }, { name: "KH₂PO₄", quantity: 0.15, unit: "g", form: "Rắn", note: "30 mg/L" }, { name: "Nước cất 2 lần", quantity: 300, unit: "mL", form: "Lỏng", note: "Đong trước 300 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 300 mL nước cất", "Cân các muối cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc giấy Watman, hấp vô trùng và sử dụng"] },
  { id: "salt-2", name: "Muối 2 (10X)", group: "Stock muối", baseVolume: 500, baseUnit: "mL", stock: "10X", ingredients: [{ name: "MgCl₂·6H₂O", quantity: 1.05, unit: "g", form: "Rắn", note: "210 mg/L" }, { name: "MgSO₄·7H₂O", quantity: 0.35, unit: "g", form: "Rắn", note: "70 mg/L" }, { name: "Nước cất 2 lần", quantity: 300, unit: "mL", form: "Lỏng", note: "Đong trước 300 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 300 mL nước cất", "Cân các muối cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc giấy Watman, hấp vô trùng và sử dụng"] },
  { id: "salt-3", name: "Muối 3 (10X)", group: "Stock muối", baseVolume: 500, baseUnit: "mL", stock: "10X", ingredients: [{ name: "NaCl", quantity: 40, unit: "g", form: "Rắn", note: "8000 mg/L" }, { name: "KCl", quantity: 2, unit: "g", form: "Rắn", note: "400 mg/L" }, { name: "NaH₂PO₄·H₂O", quantity: 0.441, unit: "g", form: "Rắn", note: "88,17 mg/L" }, { name: "Na₂HPO₄", quantity: 0.602, unit: "g", form: "Rắn", note: "120,45 mg/L" }, { name: "Nước cất 2 lần", quantity: 300, unit: "mL", form: "Lỏng", note: "Đong trước 300 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 300 mL nước cất", "Cân các muối cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc giấy Watman, hấp vô trùng và sử dụng"] },
  { id: "gbss-b", name: "GBSS/B", group: "Dung dịch làm việc", baseVolume: 1000, baseUnit: "mL", stock: "Working buffer", ingredients: [{ name: "Muối 1", quantity: 100, unit: "mL", form: "Lỏng", note: "Pha vào bình 1" }, { name: "Muối 2", quantity: 100, unit: "mL", form: "Lỏng", note: "Pha vào bình 2" }, { name: "Glucose", quantity: 4, unit: "mL", form: "Lỏng" }, { name: "NaHCO₃", quantity: 4, unit: "mL", form: "Lỏng" }, { name: "CaCl₂·2H₂O", quantity: 4, unit: "mL", form: "Lỏng" }, { name: "Anti", quantity: 10, unit: "mL", form: "Lỏng", note: "100X" }, { name: "Nước cất 2 lần", quantity: 778, unit: "mL", form: "Lỏng", note: "Chia vào bình 1 và 2" }], steps: ["Đong đủ 1 L và đánh dấu vạch", "Sau hấp, tính lượng nước hao hụt rồi hút còn khoảng 780 mL và chia hai bình", "Pha Muối 1 vào bình 1, Muối 2 vào bình 2", "Trộn bình 2 vào bình 1 từ từ, vừa cho vừa lắc", "Cho các hóa chất còn lại từ từ; điều chỉnh pH 7"] },
  { id: "enzyme-buffer", name: "Enzyme Buffer (EB)", group: "Dung dịch làm việc", baseVolume: 1000, baseUnit: "mL", stock: "Working buffer", ingredients: [{ name: "Muối 3", quantity: 100, unit: "mL", form: "Lỏng", note: "10X" }, { name: "HEPES", quantity: 10, unit: "mL", form: "Lỏng", note: "100X" }, { name: "NaHCO₃", quantity: 6.17, unit: "mL", form: "Lỏng", note: "250X; 350 mg/L" }, { name: "CaCl₂·2H₂O", quantity: 9.96, unit: "mL", form: "Lỏng", note: "560 mg/L" }, { name: "Anti", quantity: 10, unit: "mL", form: "Lỏng", note: "100X" }, { name: "Nước cất 2 lần", quantity: 863.88, unit: "mL", form: "Lỏng" }], steps: ["Đong đủ 1 L và đánh dấu vạch", "Cho Muối 3 vào bình từ từ, vừa cho vừa lắc", "Cho các hóa chất còn lại từ từ", "Điều chỉnh pH 7 bằng HCl 1N hoặc NaOH 1N"] },
  { id: "egta-working", name: "EGTA working solution", group: "Dung dịch làm việc", baseVolume: 1000, baseUnit: "mL", stock: "Working buffer", ingredients: [{ name: "Muối 3", quantity: 100, unit: "mL", form: "Lỏng", note: "10X" }, { name: "HEPES", quantity: 10, unit: "mL", form: "Lỏng", note: "100X" }, { name: "NaHCO₃", quantity: 6.17, unit: "mL", form: "Lỏng", note: "250X; 350 mg/L" }, { name: "EGTA", form: "Lỏng", note: "Theo công thức gốc chưa có lượng chuẩn" }, { name: "Glucose", quantity: 3.63, unit: "mL", form: "Lỏng", note: "250X; 900 mg/L" }, { name: "Anti", quantity: 10, unit: "mL", form: "Lỏng", note: "100X" }, { name: "Nước cất 2 lần", quantity: 870.2, unit: "mL", form: "Lỏng" }], steps: ["Đong đủ 1 L và đánh dấu vạch", "Cho Muối 3 vào bình từ từ, vừa cho vừa lắc", "Cho các hóa chất còn lại từ từ", "Điều chỉnh pH 7; bổ sung EGTA theo SOP đã chuẩn hóa"] },
  { id: "anesthetic", name: "Thuốc mê", group: "Dung dịch sử dụng", baseVolume: 800, baseUnit: "µL", stock: "Tỉ lệ 5:3", note: "Không vô trùng; liều tham chiếu 40 mg / 25 g", ingredients: [{ name: "Zoletil", quantity: 500, unit: "µL", form: "Lỏng" }, { name: "Xyla", quantity: 300, unit: "µL", form: "Lỏng" }], steps: ["Pha theo tỉ lệ 5:3 và sử dụng", "Không cần vô trùng"] },
];
