import { useMemo, useState } from "react";
import { Beaker, Calculator, Check, FlaskConical, Info, Table2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type ChemicalUnit = "L" | "mL" | "µL";
type ChemicalIngredient = { name: string; quantity?: number; unit?: ChemicalUnit | "g" | "gói" | "phần"; form: string; note?: string; finalTopUp?: boolean };
type ChemicalRecipe = { id: string; name: string; group: string; baseVolume: number; baseUnit: ChemicalUnit; stock: string; note?: string; ingredients: ChemicalIngredient[]; steps: string[] };

const recipes: ChemicalRecipe[] = [
  { id: "pbs", name: "PBS", group: "Dung dịch cơ bản", baseVolume: 1000, baseUnit: "mL", stock: "—", ingredients: [{ name: "Nước cất 2 lần", quantity: 1000, unit: "mL", form: "Lỏng" }, { name: "Gói bột PBS", quantity: 1, unit: "gói", form: "Rắn" }], steps: ["Khuấy tan bột và nước", "Lọc giấy lọc Watman", "Hấp vô trùng và sử dụng"] },
  { id: "glucose", name: "Glucose (250X)", group: "Stock đơn chất", baseVolume: 50, baseUnit: "mL", stock: "250X = 247,75 g/L", note: "Lọc màng 0,22 µm, không hấp", ingredients: [{ name: "Glucose", quantity: 12.388, unit: "g", form: "Rắn", note: "Final conc. 991 mg/L" }, { name: "Nước cất 2 lần", quantity: 40, unit: "mL", form: "Lỏng", note: "Đong trước 40 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 40 mL nước cất", "Cân glucose cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc màng 0,22 µm vô trùng"] },
  { id: "nahco3", name: "NaHCO₃ (250X)", group: "Stock đơn chất", baseVolume: 50, baseUnit: "mL", stock: "250X = 56,75 g/L", note: "Lọc màng 0,22 µm, không hấp", ingredients: [{ name: "NaHCO₃", quantity: 2.838, unit: "g", form: "Rắn", note: "Final conc. 227 mg/L" }, { name: "Nước cất 2 lần", quantity: 40, unit: "mL", form: "Lỏng", note: "Đong trước 40 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 40 mL nước cất", "Cân NaHCO₃ cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc màng 0,22 µm vô trùng"] },
  { id: "cacl2", name: "CaCl₂·2H₂O (250X)", group: "Stock đơn chất", baseVolume: 50, baseUnit: "mL", stock: "250X = 56,25 g/L", ingredients: [{ name: "CaCl₂·2H₂O", quantity: 2.813, unit: "g", form: "Rắn", note: "Final conc. 225 mg/L" }, { name: "Nước cất 2 lần", quantity: 40, unit: "mL", form: "Lỏng", note: "Đong trước 40 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 40 mL nước cất", "Cân CaCl₂·2H₂O cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc giấy lọc Watman và hấp vô trùng"] },
  { id: "hepes", name: "HEPES (100X)", group: "Stock đơn chất", baseVolume: 50, baseUnit: "mL", stock: "100X = 595 g/L", note: "Lọc màng 0,22 µm, không hấp", ingredients: [{ name: "HEPES", quantity: 11.9, unit: "g", form: "Rắn", note: "Final conc. 2380 mg/L" }, { name: "Nước cất 2 lần", quantity: 40, unit: "mL", form: "Lỏng", note: "Đong trước 40 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 40 mL nước cất", "Cân HEPES cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Điều chỉnh pH 7 bằng HCl 1N hoặc NaOH 1N, rồi lọc"] },
  { id: "egta-stock", name: "EGTA (250X)", group: "Stock đơn chất", baseVolume: 50, baseUnit: "mL", stock: "250X = 47,5 g/L", note: "Lọc màng 0,22 µm, không hấp", ingredients: [{ name: "EGTA", quantity: 2.375, unit: "g", form: "Rắn", note: "Final conc. 190 mg/L" }, { name: "Nước cất 2 lần", quantity: 40, unit: "mL", form: "Lỏng", note: "Đong trước 40 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 40 mL nước cất", "Cân EGTA cho vào khuấy tan", "Điều chỉnh pH 7 bằng NaOH từ từ", "Đong nước cất lên đủ thể tích và lọc màng"] },
  { id: "antibiotic", name: "Antibiotic (100X)", group: "Stock hỗn hợp", baseVolume: 100, baseUnit: "mL", stock: "100X", note: "Không hấp; pha theo tỉ lệ 1:3", ingredients: [{ name: "Streptomycin", quantity: 1, unit: "phần", form: "Rắn", note: "Tỉ lệ 1" }, { name: "Gentamicin", quantity: 3, unit: "phần", form: "Lỏng", note: "Tỉ lệ 3" }, { name: "Nước cất vô trùng", quantity: 100, unit: "mL", form: "Lỏng", note: "50 mL trước + 50 mL còn lại" }], steps: ["Cho trước 50 mL nước cất vô trùng", "Cho hai chất kháng sinh vào", "Cho 50 mL nước cất còn lại và sử dụng"] },
  { id: "nycodenz", name: "Nycodenz (80%)", group: "Stock đơn chất", baseVolume: 100, baseUnit: "mL", stock: "80% w/v → 1,426 g/mL", note: "Lọc màng 0,22 µm, không hấp", ingredients: [{ name: "Nycodenz", quantity: 80, unit: "g", form: "Rắn" }, { name: "Nước cất 2 lần", quantity: 50, unit: "mL", form: "Lỏng", note: "Đong trước 50 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 50 mL nước cất", "Cân Nycodenz cho vào khuấy tan", "Đong nước cất lên đủ thể tích và lọc màng"] },
  { id: "salt-1", name: "Muối 1 (10X)", group: "Stock muối", baseVolume: 500, baseUnit: "mL", stock: "10X", ingredients: [{ name: "NaCl", quantity: 40, unit: "g", form: "Rắn", note: "8000 mg/L" }, { name: "KCl", quantity: 1.85, unit: "g", form: "Rắn", note: "370 mg/L" }, { name: "Na₂HPO₄", quantity: 0.298, unit: "g", form: "Rắn", note: "59,6 mg/L" }, { name: "KH₂PO₄", quantity: 0.15, unit: "g", form: "Rắn", note: "30 mg/L" }, { name: "Nước cất 2 lần", quantity: 300, unit: "mL", form: "Lỏng", note: "Đong trước 300 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 300 mL nước cất", "Cân các muối cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc giấy Watman, hấp vô trùng và sử dụng"] },
  { id: "salt-2", name: "Muối 2 (10X)", group: "Stock muối", baseVolume: 500, baseUnit: "mL", stock: "10X", ingredients: [{ name: "MgCl₂·6H₂O", quantity: 1.05, unit: "g", form: "Rắn", note: "210 mg/L" }, { name: "MgSO₄·7H₂O", quantity: 0.35, unit: "g", form: "Rắn", note: "70 mg/L" }, { name: "Nước cất 2 lần", quantity: 300, unit: "mL", form: "Lỏng", note: "Đong trước 300 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 300 mL nước cất", "Cân các muối cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc giấy Watman, hấp vô trùng và sử dụng"] },
  { id: "salt-3", name: "Muối 3 (10X)", group: "Stock muối", baseVolume: 500, baseUnit: "mL", stock: "10X", ingredients: [{ name: "NaCl", quantity: 40, unit: "g", form: "Rắn", note: "8000 mg/L" }, { name: "KCl", quantity: 2, unit: "g", form: "Rắn", note: "400 mg/L" }, { name: "NaH₂PO₄·H₂O", quantity: 0.441, unit: "g", form: "Rắn", note: "88,17 mg/L" }, { name: "Na₂HPO₄", quantity: 0.602, unit: "g", form: "Rắn", note: "120,45 mg/L" }, { name: "Nước cất 2 lần", quantity: 300, unit: "mL", form: "Lỏng", note: "Đong trước 300 mL; sau đó lên đủ thể tích" }], steps: ["Đong trước 300 mL nước cất", "Cân các muối cho vào khuấy tan", "Đong nước cất lên đủ thể tích", "Lọc giấy Watman, hấp vô trùng và sử dụng"] },
  { id: "gbss-b", name: "GBSS/B", group: "Dung dịch làm việc", baseVolume: 1000, baseUnit: "mL", stock: "Working buffer", ingredients: [{ name: "Muối 1", quantity: 100, unit: "mL", form: "Lỏng", note: "Pha vào bình 1" }, { name: "Muối 2", quantity: 100, unit: "mL", form: "Lỏng", note: "Pha vào bình 2" }, { name: "Glucose", quantity: 4, unit: "mL", form: "Lỏng" }, { name: "NaHCO₃", quantity: 4, unit: "mL", form: "Lỏng" }, { name: "CaCl₂·2H₂O", quantity: 4, unit: "mL", form: "Lỏng" }, { name: "Anti", quantity: 10, unit: "mL", form: "Lỏng", note: "100X" }, { name: "Nước cất 2 lần", quantity: 778, unit: "mL", form: "Lỏng", note: "Chia vào bình 1 và 2" }], steps: ["Đong đủ 1 L và đánh dấu vạch", "Sau hấp, tính lượng nước hao hụt rồi hút còn khoảng 780 mL và chia hai bình", "Pha Muối 1 vào bình 1, Muối 2 vào bình 2", "Trộn bình 2 vào bình 1 từ từ, vừa cho vừa lắc", "Cho các hóa chất còn lại từ từ; điều chỉnh pH 7"] },
  { id: "enzyme-buffer", name: "Enzyme Buffer (EB)", group: "Dung dịch làm việc", baseVolume: 1000, baseUnit: "mL", stock: "Working buffer", ingredients: [{ name: "Muối 3", quantity: 100, unit: "mL", form: "Lỏng", note: "10X" }, { name: "HEPES", quantity: 10, unit: "mL", form: "Lỏng", note: "100X" }, { name: "NaHCO₃", quantity: 6.17, unit: "mL", form: "Lỏng", note: "250X; 350 mg/L" }, { name: "CaCl₂·2H₂O", quantity: 9.96, unit: "mL", form: "Lỏng", note: "560 mg/L" }, { name: "Anti", quantity: 10, unit: "mL", form: "Lỏng", note: "100X" }, { name: "Nước cất 2 lần", quantity: 863.88, unit: "mL", form: "Lỏng" }], steps: ["Đong đủ 1 L và đánh dấu vạch", "Cho Muối 3 vào bình từ từ, vừa cho vừa lắc", "Cho các hóa chất còn lại từ từ", "Điều chỉnh pH 7 bằng HCl 1N hoặc NaOH 1N"] },
  { id: "egta-working", name: "EGTA working solution", group: "Dung dịch làm việc", baseVolume: 1000, baseUnit: "mL", stock: "Working buffer", ingredients: [{ name: "Muối 3", quantity: 100, unit: "mL", form: "Lỏng", note: "10X" }, { name: "HEPES", quantity: 10, unit: "mL", form: "Lỏng", note: "100X" }, { name: "NaHCO₃", quantity: 6.17, unit: "mL", form: "Lỏng", note: "250X; 350 mg/L" }, { name: "EGTA", form: "Lỏng", note: "Theo công thức gốc chưa có lượng chuẩn" }, { name: "Glucose", quantity: 3.63, unit: "mL", form: "Lỏng", note: "250X; 900 mg/L" }, { name: "Anti", quantity: 10, unit: "mL", form: "Lỏng", note: "100X" }, { name: "Nước cất 2 lần", quantity: 870.2, unit: "mL", form: "Lỏng" }], steps: ["Đong đủ 1 L và đánh dấu vạch", "Cho Muối 3 vào bình từ từ, vừa cho vừa lắc", "Cho các hóa chất còn lại từ từ", "Điều chỉnh pH 7; bổ sung EGTA theo SOP đã chuẩn hóa"] },
  { id: "anesthetic", name: "Thuốc mê", group: "Dung dịch sử dụng", baseVolume: 800, baseUnit: "µL", stock: "Tỉ lệ 5:3", note: "Không vô trùng; liều tham chiếu 40 mg / 25 g", ingredients: [{ name: "Zoletil", quantity: 500, unit: "µL", form: "Lỏng" }, { name: "Xyla", quantity: 300, unit: "µL", form: "Lỏng" }], steps: ["Pha theo tỉ lệ 5:3 và sử dụng", "Không cần vô trùng"] },
];

const format = (value: number) => new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 4 }).format(value);
const toMl = (value: number, unit: ChemicalUnit) => unit === "L" ? value * 1000 : unit === "µL" ? value / 1000 : value;
const fromMl = (value: number, unit: ChemicalUnit) => unit === "L" ? value / 1000 : unit === "µL" ? value * 1000 : value;

export function ChemicalMixingView({ initialTab = "chemicals" }: { initialTab?: "chemicals" | "stock" }) {
  const [tab, setTab] = useState<"chemicals" | "stock">(initialTab);
  const [selectedId, setSelectedId] = useState(recipes[0].id);
  const [totalVolume, setTotalVolume] = useState(String(recipes[0].baseVolume));
  const [totalUnit, setTotalUnit] = useState<ChemicalUnit>(recipes[0].baseUnit);
  const [checked, setChecked] = useState<Set<string>>(new Set());
  const selected = recipes.find(recipe => recipe.id === selectedId) ?? recipes[0];
  const scale = useMemo(() => {
    const desiredMl = toMl(Number(totalVolume.replace(",", ".")), totalUnit);
    return Number.isFinite(desiredMl) && desiredMl > 0 ? desiredMl / toMl(selected.baseVolume, selected.baseUnit) : null;
  }, [selected, totalUnit, totalVolume]);
  const chooseRecipe = (id: string) => {
    const recipe = recipes.find(item => item.id === id) ?? recipes[0];
    setSelectedId(recipe.id); setTotalVolume(String(recipe.baseVolume)); setTotalUnit(recipe.baseUnit);
  };
  const toggleCheck = (id: string) => setChecked(current => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  return <div className="chemical-page">
    <PageIntro eyebrow="CHEMISTRY WORKBENCH" title={<>Pha <em>hoá chất.</em></>} description="Tính nhanh lượng cần cân/đong theo tổng thể tích và tra cứu các công thức stock đã chuẩn hóa." />
    <div className="chemical-tabs" role="tablist" aria-label="Pha hoá chất">
      <button className={tab === "chemicals" ? "active" : ""} onClick={() => setTab("chemicals")}><Calculator size={16} /> Hoá chất</button>
      <button className={tab === "stock" ? "active" : ""} onClick={() => setTab("stock")}><Table2 size={16} /> Hoá chất stock <span>{recipes.length}</span></button>
    </div>
    {tab === "chemicals" ? <div className="chemical-workspace">
      <aside className="chemical-recipe-list content-panel"><div className="panel-index">RECIPES / {recipes.length}</div>{recipes.map(recipe => <button key={recipe.id} className={recipe.id === selected.id ? "active" : ""} onClick={() => chooseRecipe(recipe.id)}><span className="chemical-dot" /><span><strong>{recipe.name}</strong><small>{recipe.group} · {recipe.baseVolume} {recipe.baseUnit}</small></span></button>)}</aside>
      <section className="chemical-calculator"><div className="content-panel chemical-input-panel"><div className="panel-index">TARGET VOLUME</div><div className="chemical-heading"><div><h2>{selected.name}</h2><p>{selected.stock}{selected.note ? ` · ${selected.note}` : ""}</p></div><FlaskConical size={28} /></div><div className="chemical-input-row"><label className="field-label">Tổng thể tích cần<Input value={totalVolume} onChange={event => setTotalVolume(event.target.value)} inputMode="decimal" /><small>Công thức gốc: {selected.baseVolume} {selected.baseUnit}</small></label><label className="field-label">Đơn vị<select value={totalUnit} onChange={event => setTotalUnit(event.target.value as ChemicalUnit)}><option value="L">L</option><option value="mL">mL</option><option value="µL">µL</option></select></label></div>{scale === null && <div className="chemical-warning"><Info size={15} /> Nhập tổng thể tích dương để tính.</div>}</div><div className="content-panel chemical-result-panel"><div className="panel-heading"><div><span className="panel-index">RESULT / SCALED AMOUNTS</span><h2>Lượng cần cân / đong</h2></div>{scale !== null && <span className="chemical-scale">× {format(scale)}</span>}</div><div className="chemical-table-wrap"><table className="chemical-table"><thead><tr><th>Hoá chất</th><th>Form</th><th>Lượng cần</th><th>Ghi chú</th></tr></thead><tbody>{selected.ingredients.map((ingredient, index) => { const quantity = scale !== null && ingredient.quantity !== undefined ? ingredient.quantity * scale : null; const displayed = quantity === null ? "Theo SOP" : `${format(ingredient.unit === "g" || ingredient.unit === "gói" || ingredient.unit === "phần" ? quantity : quantity)} ${ingredient.unit ?? ""}`; return <tr key={`${ingredient.name}-${index}`}><td><strong>{ingredient.name}</strong></td><td>{ingredient.form}</td><td className="chemical-amount">{displayed}</td><td>{ingredient.note ?? (ingredient.finalTopUp ? "Bổ sung đến đủ thể tích" : "")}</td></tr>; })}</tbody></table></div><div className="chemical-method"><div className="panel-index">METHOD / NOTES</div><ol>{selected.steps.map((step, index) => <li key={index}>{step}</li>)}</ol></div></div></section>
    </div> : <section className="content-panel stock-panel"><div className="panel-heading"><div><span className="panel-index">STOCK LIBRARY / {recipes.length} RECIPES</span><h2>Bảng pha hoá chất stock</h2><p className="stock-intro">Chọn một công thức để chuyển sang tab Hoá chất và scale theo tổng thể tích cần pha.</p></div><span className="stock-summary"><Check size={14} /> {checked.size}/{recipes.length} đã rà</span></div><div className="chemical-table-wrap"><table className="chemical-table stock-table"><thead><tr><th>Rà</th><th>Công thức</th><th>Nhóm</th><th>Thể tích gốc</th><th>Stock / ghi chú</th><th>Thành phần chính</th><th></th></tr></thead><tbody>{recipes.map(recipe => <tr key={recipe.id}><td><input type="checkbox" checked={checked.has(recipe.id)} onChange={() => toggleCheck(recipe.id)} aria-label={`Đánh dấu ${recipe.name}`} /></td><td><strong>{recipe.name}</strong></td><td>{recipe.group}</td><td>{recipe.baseVolume} {recipe.baseUnit}</td><td>{recipe.stock}{recipe.note ? <small>{recipe.note}</small> : null}</td><td><div className="stock-ingredients">{recipe.ingredients.map(item => <span key={item.name}>{item.name}{item.quantity !== undefined ? ` · ${item.quantity} ${item.unit}` : ""}</span>)}</div></td><td><Button variant="outline" onClick={() => { chooseRecipe(recipe.id); setTab("chemicals"); }}>Pha</Button></td></tr>)}</tbody></table></div></section>}
  </div>;
}

function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: React.ReactNode; description: string }) {
  return <div className="page-intro"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div></div>;
}
